.TH NOTEPAD 1 "November 2010" "Wine 8.4" "Wine Programs"
.SH NAME
notepad \- Wine text editor
.SH SYNOPSIS
.B notepad
.RI [ text\ file ]
.SH DESCRIPTION
.B notepad
is the Wine text editor, designed to be compatible with its Microsoft Windows counterpart.
It supports ANSI, UTF-8 and UTF-16 files, and can read (but not write) files with Unix line endings.
.SH BUGS
Bugs can be reported on the
.UR https://bugs.winehq.org
.B Wine bug tracker
.UE .
.SH AVAILABILITY
.B notepad
is part of the Wine distribution, which is available through WineHQ,
the
.UR https://www.winehq.org/
.B Wine development headquarters
.UE .
.SH "SEE ALSO"
.BR wine (1),
.br
.UR https://www.winehq.org/help
.B Wine documentation and support
.UE .
