.TH WINEFILE 1 "November 2010" "Wine 8.4" "Wine Programs"
.SH NAME
winefile \- Wine File Manager
.SH SYNOPSIS
.BI winefile " path"
.SH DESCRIPTION
.B winefile
is the Wine file manager, with a similar design to early Microsoft Windows explorer.
.SH USAGE
You can pass winefile either a Unix or Win32 path, for example:

.RB "Using a Unix path:  " "winefile /mnt/hda1"

.RB "Using a Win32 path: " "winefile C:\(rs\(rswindows\(rs\(rs\"

.SH BUGS
Bugs can be reported on the
.UR https://bugs.winehq.org
.B Wine bug tracker
.UE .
.SH AVAILABILITY
.B winefile
is part of the Wine distribution, which is available through WineHQ,
the
.UR https://www.winehq.org/
.B Wine development headquarters
.UE .
.SH "SEE ALSO"
.BR wine (1),
.br
.UR https://www.winehq.org/help
.B Wine documentation and support
.UE .
