.TH WINECONSOLE 1 "November 2010" "Wine 8.4" "Wine Programs"
.SH NAME
wineconsole \- The Wine console
.SH SYNOPSIS
.B wineconsole
.RI [ command "] "
.SH DESCRIPTION
.B wineconsole
is the Wine console manager, used to run console commands and applications. It allows running the
console in a newly made window.
.SH BUGS
Bugs can be reported on the
.UR https://bugs.winehq.org
.B Wine bug tracker
.UE .
.SH AVAILABILITY
.B wineconsole
is part of the Wine distribution, which is available through WineHQ,
the
.UR https://www.winehq.org/
.B Wine development headquarters
.UE .
.SH "SEE ALSO"
.BR wine (1),
.br
.UR https://www.winehq.org/help
.B Wine documentation and support
.UE .
