.TH WINEMINE 1 "November 2010" "Wine 8.4" "Wine Programs"
.SH NAME
winemine \- Wine Minesweeper game
.SH SYNOPSIS
.BR winemine
.SH DESCRIPTION
.B winemine
is the Wine Minesweeper game. The object of the game is to try to find all the hidden mines by
uncovering the tiles to see how many mines each tile is adjacent to, without uncovering a mine.
.SH BUGS
Bugs can be reported on the
.UR https://bugs.winehq.org
.B Wine bug tracker
.UE .
.SH AVAILABILITY
.B winemine
is part of the Wine distribution, which is available through WineHQ,
the
.UR https://www.winehq.org/
.B Wine development headquarters
.UE .
.SH "SEE ALSO"
.BR wine (1),
.br
.UR https://www.winehq.org/help
.B Wine documentation and support
.UE .
