.TH WINEBOOT 1 "November 2010" "Wine 8.4" "Wine Programs"
.SH NAME
wineboot \- perform Wine initialization, startup, and shutdown tasks
.SH SYNOPSIS
.B wineboot
.RI [ options ]
.SH DESCRIPTION
.B wineboot
performs the initial creation and setup of a WINEPREFIX for wine(1). It can also perform a simulated
reboot or shutdown to any applications running within the WINEPREFIX.
.SH "OPTIONS"
.IP \fB\-h\fR,\fB\ \-\-help
Display help message.
.IP \fB\-e\fR,\fB\ \-\-end\-session
End the current session cleanly.
.IP \fB\-f\fR,\fB\ \-\-force
Force exit for processes that don't exit cleanly
.IP \fB\-i\fR,\fB\ \-\-init
Initialize the WINEPREFIX.
.IP \fB\-k\fR,\fB\ \-\-kill
Kill running processes without any cleanup.
.IP \fB\-r\fR,\fB\ \-\-restart
Restart only, don't do normal startup operations.
.IP \fB\-s\fR,\fB\ \-\-shutdown
Shutdown only, don't reboot.
.IP \fB\-u\fR,\fB\ \-\-update
Update the WINEPREFIX.
.SH BUGS
Bugs can be reported on the
.UR https://bugs.winehq.org
.B Wine bug tracker
.UE .
.SH AVAILABILITY
.B wineboot
is part of the Wine distribution, which is available through WineHQ,
the
.UR https://www.winehq.org/
.B Wine development headquarters
.UE .
.SH "SEE ALSO"
.BR wine (1),
.br
.UR https://www.winehq.org/help
.B Wine documentation and support
.UE .
