name: Bug Report
description: Report a bug.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide detailed step-by-step instructions on how to reproduce this issue.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: Please provide a clear a detailed description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: whisky-version
    attributes:
      label: What version of Whisky are you using?
      options:
        - "pre-0.2.4"
        - "pre-0.2.3"
        - "pre-0.2.2"
        - "pre-0.2.1"
        - "pre-0.2.0"
        - "<pre-0.2.0"
    validations:
      required: true
  - type: dropdown
    id: mac-version
    attributes:
      label: What version of macOS are you using?
      options:
        - "Ventura (macOS 13)"
        - "Sonoma (macOS 14)"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Issue Language
      description: All issues must be written in clear plain English so that all devs are able to read them.
      options:
        - label: Yes my issue is written in English
          required: true
